name: DrawMyThing
main: Epic\Dmt\Main
version: 1.1
api: [3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.1, 3.0.0]
author: Zeao
description: DrawMyThing Mini-Game, ported to MCPE. The old developer is no longer working on this project. I am now taking over it as of now.
commands:
    dmt:
        usage: /dmt
        description: Run the dmt command
